name: Trivy Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trivy-secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy secret scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          exit-code: 1
          ignore-unfixed: true
          hide-progress: true